### ISSUE TITLE
Question: How to apply binary diff, when you don't have an external flash and you need to do it on internal flash.

### ISSUE THREAD

**Issue by yogeshk19** [janjongboom/binary-diff-mbedos5#1]
Hi Jan,

I am not sure if you are monitoring this repository any longer. Anyway I thought just incase I will ask my question :).  We are planning on transmitting firmware updates over LORAWAN. We currently have a custom board, which has an mDot and BLE Module. So we want to transmit firmware updates to both the mDot and BLE Module. I came across this repository which demonstrates the example for using an external SD card or flash to eventually merge the diff file with the original file. How would I go about doing it on the internal flash using the FlashIAP API in mbed os 5. We eventually plan on adding an external flash to the BLE Module, but until then I was wondering if you have any suggestions, how I could extend your BDFile to support internal flash too?

Thanks,
Yogesh

**Comment by janjongboom** [comment]
Hi @yogeshk19 Sorry never saw this thread, but in case someone else is finding this as well :-) You can use FlashIAP through the `FlashIAPBlockDevice` and then use https://github.com/janjongboom/binary-diff-mbedos5/blob/xdot/src/main.cpp#L52 which demonstrates applying a patch on any `BlockDevice`. Note that you **cannot reliably read the current application** while the application is running through FlashIAP, so to read current application you'll need a bootloader. The `xdot` branch in https://github.com/janjongboom/binary-diff-mbedos5/ has an example of this.
